/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20 from "./erc20";
export type { erc20 };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as lendborrow from "./lendborrow";
export type { lendborrow };
import type * as proxy from "./proxy";
export type { proxy };
import type * as uniswap from "./uniswap";
export type { uniswap };
export type { Migrations } from "./Migrations";
