/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IQuadraticBorrowCompound } from "./IQuadraticBorrowCompound";
export type { IQuadraticLendCompound } from "./IQuadraticLendCompound";
export type { IQuadraticLiquidation } from "./IQuadraticLiquidation";
