/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QuadraticBorrowCompound } from "./QuadraticBorrowCompound";
export type { QuadraticFinanceToken } from "./QuadraticFinanceToken";
export type { QuadraticLendCompound } from "./QuadraticLendCompound";
