/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QuadraticBorrowCompoundProxy } from "./QuadraticBorrowCompoundProxy";
export type { QuadraticLendCompoundProxy } from "./QuadraticLendCompoundProxy";
export type { UniswapV3ChainLinkOracleProxy } from "./UniswapV3ChainLinkOracleProxy";
