/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapV3ChainLinkUsdOracleSol from "./UniswapV3ChainLinkUsdOracle.sol";
export type { uniswapV3ChainLinkUsdOracleSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { IUniswapV3Oracle } from "./IUniswapV3Oracle";
