/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IQuadraticBorrowCompound__factory } from "./IQuadraticBorrowCompound__factory";
export { IQuadraticLendCompound__factory } from "./IQuadraticLendCompound__factory";
export { IQuadraticLiquidation__factory } from "./IQuadraticLiquidation__factory";
