/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IQuadraticLiquidation,
  IQuadraticLiquidationInterface,
} from "../../../contracts/interfaces/IQuadraticLiquidation";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "bid",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "erc721",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "targetToken",
        type: "address",
      },
    ],
    name: "disposalNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IQuadraticLiquidation__factory {
  static readonly abi = _abi;
  static createInterface(): IQuadraticLiquidationInterface {
    return new Interface(_abi) as IQuadraticLiquidationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IQuadraticLiquidation {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IQuadraticLiquidation;
  }
}
