/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IQuadraticAuction,
  IQuadraticAuctionInterface,
} from "../../../contracts/interfaces/IQuadraticAuction";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "erc721Addr",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "bid",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "auctionToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "startAuctionAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "startAuctioInterests",
        type: "uint256",
      },
    ],
    name: "toAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IQuadraticAuction__factory {
  static readonly abi = _abi;
  static createInterface(): IQuadraticAuctionInterface {
    return new Interface(_abi) as IQuadraticAuctionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IQuadraticAuction {
    return new Contract(address, _abi, runner) as unknown as IQuadraticAuction;
  }
}
